---
- name: Show secure message
  ansible.builtin.debug:
    msg: "{{ app_message }}"

- name: Ensure deploy group exists
  ansible.builtin.group:
    name: deploy
    state: present

- name: Ensure deploy user exists
  ansible.builtin.user:
    name: deployuser
    group: deploy
    create_home: true
    shell: /bin/bash
    state: present

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - docker
    state: present

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add deploy user to docker group
  ansible.builtin.user:
    name: deployuser
    groups: docker
    append: true

- name: Pull image from Docker Hub
  command: docker pull george524/plath-custom-app:latest

- name: Remove existing container if present
  command: docker rm -f plath_custom_app
  ignore_errors: yes

- name: Run custom application container
  command: >
    docker run -d
    --name plath_custom_app
    --restart unless-stopped
    -p 80:80
    george524/plath-custom-app:latest