---
- name: Show secure message
  ansible.builtin.debug:
    msg: "{{ app_message }}"

- name: Ensure deploy group exists
  ansible.builtin.group:
    name: deploy
    state: present

- name: Ensure deploy user exists
  ansible.builtin.user:
    name: deployuser
    group: deploy
    create_home: true
    shell: /bin/bash
    state: present

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - docker
    state: present

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add deploy user to docker group
  ansible.builtin.user:
    name: deployuser
    groups: docker
    append: true

- name: Pull target application image
  ansible.builtin.command: docker pull {{ app_image }}

- name: Remove old demo nginx container if present
  ansible.builtin.command: docker rm -f demo_nginx
  register: remove_demo_nginx
  failed_when: false
  changed_when: remove_demo_nginx.rc == 0

- name: Remove existing application container if present
  ansible.builtin.command: docker rm -f plath_custom_app
  register: remove_container
  failed_when: false
  changed_when: remove_container.rc == 0

- name: Run custom application container
  ansible.builtin.command: >
    docker run -d
    --name plath_custom_app
    --restart unless-stopped
    -p 80:80
    {{ app_image }}
  changed_when: true
- name: Pull Flask backend image
  ansible.builtin.command: docker pull {{ flask_image }}

- name: Remove existing Flask container if present
  ansible.builtin.command: docker rm -f magvector_flask
  register: remove_flask
  failed_when: false
  changed_when: remove_flask.rc == 0

- name: Run Flask backend container
  ansible.builtin.command: >
    docker run -d
    --name magvector_flask
    --restart unless-stopped
    -p 5000:5000
    -e DB_HOST={{ db_host }}
    -e DB_NAME={{ db_name }}
    -e DB_USER={{ db_user }}
    -e DB_PASSWORD={{ vault_db_password }}
    -e DB_PORT={{ db_port }}
    {{ flask_image }}
  changed_when: true
